runtime: custom
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:tG8vGM7xkKXlo7Pwra0oqgsbIneLYEiSDYqKJ6BejmI=
  APP_NAME: "Male-Fashion"

  #   DB_DATABASE: malefashion
  #   DB_USERNAME: root
  #   DB_PASSWORD: password
  #   DB_SOCKET: /cloudsql/cloud-computing-364304:asia-southeast2:mysql

  LOG_LEVEL: debug
# beta_settings:
#   cloud_sql_instances: "cloud-computing-364304:asia-southeast2:mysql"
